/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A dimension handle that combines .idx and .bin file access.
 *
 * On construction, both files are mmap'd and validated. All query methods
 * are synchronous and zero-copy — pack data is read directly from the mmap.
 */
export declare class DimensionHandle {
  /**
   * Create a new DimensionHandle by opening and mmap'ing the .idx and .bin files.
   *
   * Validates both file headers (PFXI magic for .idx, PFSP magic for .bin).
   * Throws a JS Error on invalid paths or unsupported formats.
   */
  constructor(idxPath: string, binPath: string)
  /** Return the number of records in the .idx file. */
  recordCount(): number
  /**
   * Query a single (concreteLineId, handId) pair.
   *
   * Returns `null` if the concreteLineId is not found or the handId is not
   * present in the pack. When `verify_checksum` is true, the pack CRC32C
   * is validated before decoding.
   */
  query(concreteLineId: number, handId: number, verifyChecksum?: boolean | undefined | null): PackDecodeResult | null
  /**
   * Batch query multiple (concreteLineId, handId) pairs.
   *
   * Returns an array of the same length as `requests`. Each element is
   * `null` if the corresponding concreteLineId is not found or the handId
   * is not in the pack.
   */
  queryBatch(requests: Array<BatchQueryRequest>, verifyChecksum?: boolean | undefined | null): Array<PackDecodeResult | undefined | null>
  /**
   * Return the unique action_schema_id values used by this dimension.
   *
   * Enables the TS layer to prewarm only the subset of action schemas
   * actually referenced, avoiding full-schema eager loading.
   */
  uniqueActionSchemaIds(): Array<number>
  /**
   * Flat binary batch query — returns a raw Buffer to avoid napi object
   * serialization overhead for `DecodedCellResult` objects.
   *
   * Buffer layout (all little-endian):
   *   HEADER (12 bytes):
   *     [0..4)   magic: u32 = 0x46425146 ("FQBF")
   *     [4..8)   requestCount: u32
   *     [8..12)  hitCount: u32
   *   PER-REQUEST TABLE (requestCount × 8 bytes):
   *     [0..2)   cellCount: u16  (0 = null/miss)
   *     [2..4)   reserved: u16 = 0
   *     [4..8)   actionSchemaId: u32
   *   CELL DATA (totalCellCount × 21 bytes):
   *     [0..4)   actionId: u32
   *     [4..12)  frequency: f64
   *     [12]     evFlag: u8  (1 = valid, 0 = NaN/null)
   *     [13..21) handEv: f64  (valid when evFlag=1)
   *
   * Total size = 12 + requestCount × 8 + totalCellCount × 21.
   */
  queryBatchFlat(requests: Array<BatchQueryRequest>, verifyChecksum?: boolean | undefined | null): Array<number>
  /**
   * Lightweight batch: return only action cell counts per request.
   *
   * Much faster than `query_batch` because it avoids serializing individual
   * DecodedCellResult objects across the napi boundary.
   * Returns `null` for a request if the concreteLineId/handId is not found.
   */
  queryBatchCount(requests: Array<BatchQueryRequest>, verifyChecksum?: boolean | undefined | null): Array<number | undefined | null>
}

/** A single request in a batch query. */
export interface BatchQueryRequest {
  concreteLineId: number
  handId: number
}

/** A decoded cell result for a single action. */
export interface DecodedCellResult {
  actionId: number
  frequency: number
  /** handEv is null (None) when the value is NaN or no EV data. */
  handEv?: number
}

/** Result of querying a pack for a specific hand. */
export interface PackDecodeResult {
  actionSchemaId: number
  cells: Array<DecodedCellResult>
}
