/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A dimension handle that combines .idx and .bin file access.
 *
 * On construction, both files are mmap'd and validated. All query methods
 * are synchronous and zero-copy — pack data is read directly from the mmap.
 */
export declare class DimensionHandle {
  /**
   * Create a new DimensionHandle by opening and mmap'ing the .idx and .bin files.
   *
   * Validates both file headers (PFXI magic for .idx, PFSP magic for .bin).
   * Throws a JS Error on invalid paths or unsupported formats.
   */
  constructor(idxPath: string, binPath: string)
  /** Return the number of records in the .idx file. */
  recordCount(): number
  /**
   * Query a single (concreteLineId, handId) pair.
   *
   * Returns `null` if the concreteLineId is not found or the handId is not
   * present in the pack. When `verify_checksum` is true, the pack CRC32C
   * is validated before decoding.
   */
  query(concreteLineId: number, handId: number, verifyChecksum?: boolean | undefined | null): PackDecodeResult | null
  /**
   * Batch query multiple (concreteLineId, handId) pairs.
   *
   * Returns an array of the same length as `requests`. Each element is
   * `null` if the corresponding concreteLineId is not found or the handId
   * is not in the pack.
   */
  queryBatch(requests: Array<BatchQueryRequest>, verifyChecksum?: boolean | undefined | null): Array<PackDecodeResult | undefined | null>
}

/** A single request in a batch query. */
export interface BatchQueryRequest {
  concreteLineId: number
  handId: number
}

/** A decoded cell result for a single action. */
export interface DecodedCellResult {
  actionId: number
  frequency: number
  /** handEv is null (None) when the value is NaN or no EV data. */
  handEv?: number
}

/** Result of querying a pack for a specific hand. */
export interface PackDecodeResult {
  actionSchemaId: number
  cells: Array<DecodedCellResult>
}
